userdel usu_1ESO
userdel usu_2ESO
userdel usu_3ESO
userdel usu_4ESO
userdel usu_1BACH
userdel usu_2BACH
userdel usu_DAM
userdel profesorado
userdel alumnado

groupdel Publico_rwx
groupdel Publico_rx
groupdel ESO_rx
groupdel BACH_rx
groupdel 1ESO
groupdel 2ESO
groupdel 3ESO
groupdel 4ESO
groupdel 1BACH
groupdel 2BACH
groupdel DAM
groupdel 1ESO_rwx
groupdel 2ESO_rwx
groupdel 3ESO_rwx
groupdel 4ESO_rwx
groupdel 1BACH_rwx
groupdel 2BACH_rwx
groupdel DAM_rwx
